# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ea52b3b404d4c0a5565571d3cedb80d2a0d2b12d89abb8110fa842ecacf68316f6bd1db1e8c0829d29b1e23c48d640b077c67adfb441ca2e575019ae594fb49

test:
  secret_key_base: e012d484e93d12faf92344b19d1e93c616a5b1146d8ba7e61d753079eeee74ebce9c1f5dbbb45fc447e1dab223d79e05d40a94ad11d107bdd7b32f996634adfd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
